import { people, projectLinks } from './links';

export default function Home() {
  return <main id="top">
    <a className="skipLink" href="#team">Skip to the team</a>
    <header className="nav wrap"><a className="brand" href="#top">trash<span>UQ</span><i /></a><a href="#team">Meet the team ↓</a></header>
    <section className="hero wrap" aria-labelledby="hero-title">
      <div className="heroCopy"><p className="eyebrow">● BUILT AT UNIVERSITAT DE LLEIDA</p><h1 id="hero-title">Small boards.<br /><span>Shared intelligence.</span></h1><p className="lede">We built TrashUQ to bring federated learning to waste monitoring. Real edge devices. Images kept local.</p><a className="primary" href="#team">Meet the people behind it <span>↓</span></a><div className="quickLinks"><a href={projectLinks.paper} target="_blank" rel="noreferrer">Read the paper ↗</a><span>/</span><a href={projectLinks.repository} target="_blank" rel="noreferrer">Explore the code ↗</a></div></div>
      <figure className="boardScene"><div className="orbit" /><div className="orbit second" /><span className="hardwareTag">01 / THE HARDWARE</span><img src="/arduino-uno-q-render.png" alt="Three-dimensional render of the Arduino UNO Q board" width={1254} height={1254} fetchPriority="high" /><figcaption>● Arduino UNO Q · Qualcomm-powered edge AI</figcaption></figure>
    </section>
    <section className="teamSection" id="team" aria-labelledby="team-title"><div className="wrap"><div className="sectionHeading"><div><p className="eyebrow">THE PEOPLE BEHIND TRASHUQ</p><h2 id="team-title">Four engineers.<br /><span>One shared idea.</span></h2></div><p>Curious about the project?<br />Let’s keep the conversation going.</p></div><div className="peopleGrid">{people.map((person,index)=><article className="personCard" key={person.name}><div className="personTop">{person.photo ? <img className="avatar avatarPhoto" src={person.photo} alt={`${person.name} profile photo`} width="104" height="104" /> : <span className={`avatar avatar${index}`} aria-hidden="true">{person.initials}</span>}<span className="personNumber">0{index+1}</span></div><h3>{person.displayName}</h3><p>TrashUQ · Co-author</p>{person.linkedin ? <a className="profileLink" href={person.linkedin} target="_blank" rel="noreferrer" aria-label={`Connect with ${person.name} on LinkedIn`}><b aria-hidden="true">in</b> Connect on LinkedIn <span>↗</span></a> : <span className="profilePending"><b aria-hidden="true">in</b> LinkedIn coming soon</span>}</article>)}</div></div></section>
    <section className="research wrap" id="research" aria-labelledby="research-title"><div className="sectionHeading"><div><p className="eyebrow">FROM IDEA TO EVIDENCE</p><h2 id="research-title">Go a little deeper.</h2></div><p>Local training on the devices.<br />Model updates shared through FedAvg.</p></div><div className="resourceGrid"><a className="resourceCard" href={projectLinks.paper} target="_blank" rel="noreferrer"><div className="resourceMeta">01 / RESEARCH PAPER <span>↗</span></div><h3>The method.<br />The experiments.<br />The results.</h3><p>Read our hardware validation and federated learning study.</p><span className="resourceAction">Open the paper <span>↗</span></span></a><a className="resourceCard codeCard" href={projectLinks.repository} target="_blank" rel="noreferrer"><div className="resourceMeta">02 / OPEN SOURCE <span>↗</span></div><h3>Get into<br />the code.</h3><p>Explore the edge runtime, coordination backend and reproducible experiments.</p><span className="resourceAction">Explore GitHub <span>↗</span></span></a></div><div className="evidence"><p><strong>2</strong><span>Edge nodes validated</span></p><p><strong>93.75%</strong><span>Accuracy in simulation</span></p><p><strong>44%</strong><span>Less communication in simulation</span></p></div><p className="evidenceNote">Simulation: 20 clients, synthetic data, means across 3 seeds. Communication savings compare 4-bit stochastic rounding with FP32.</p></section>
    <footer className="footer"><div className="wrap footerInner"><div><a className="brand" href="#top">trash<span>UQ</span></a><p>Built together. Learning together.</p><p className="supportNote">With the support and guidance of <a href="https://greia.udl.cat/" target="_blank" rel="noreferrer">GREiA</a>, a research group at the Universitat de Lleida working across artificial intelligence and sustainability. Special thanks to <a href="https://www.linkedin.com/in/jordiplanes/" target="_blank" rel="noreferrer">Jordi Planes Cid</a> for his guidance and support.</p></div><nav aria-label="Footer navigation"><a href="#team">Our team</a><a href={projectLinks.paper} target="_blank" rel="noreferrer">Paper ↗</a><a href={projectLinks.repository} target="_blank" rel="noreferrer">GitHub ↗</a></nav><small>Universitat de Lleida</small></div></footer>
  </main>;
}
