# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\tfederated\" \n\x0bJoinRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"i\n\x0cJoinResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\r\x12\x15\n\rmodel_version\x18\x04 \x01(\x04\x12\x16\n\x0eglobal_weights\x18\x05 \x03(\x02\"*\n\x15GetGlobalModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"s\n\x16GetGlobalModelResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\r\x12\x15\n\rmodel_version\x18\x04 \x01(\x04\x12\x16\n\x0eglobal_weights\x18\x05 \x03(\x02\"\x8f\x01\n\x13SubmitUpdateRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\r\x12\x13\n\x0bnum_samples\x18\x03 \x01(\r\x12\x15\n\rlocal_weights\x18\x04 \x03(\x02\x12\x12\n\nlocal_loss\x18\x05 \x01(\x02\x12\x16\n\x0elocal_accuracy\x18\x06 \x01(\x02\"{\n\x14SubmitUpdateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10round_aggregated\x18\x03 \x01(\x08\x12\x15\n\rcurrent_round\x18\x04 \x01(\r\x12\x15\n\rmodel_version\x18\x05 \x01(\x04\x32\xfb\x01\n\x18\x46\x65\x64\x65ratedLearningService\x12\x37\n\x04Join\x12\x16.federated.JoinRequest\x1a\x17.federated.JoinResponse\x12U\n\x0eGetGlobalModel\x12 .federated.GetGlobalModelRequest\x1a!.federated.GetGlobalModelResponse\x12O\n\x0cSubmitUpdate\x12\x1e.federated.SubmitUpdateRequest\x1a\x1f.federated.SubmitUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=23
  _globals['_JOINREQUEST']._serialized_end=55
  _globals['_JOINRESPONSE']._serialized_start=57
  _globals['_JOINRESPONSE']._serialized_end=162
  _globals['_GETGLOBALMODELREQUEST']._serialized_start=164
  _globals['_GETGLOBALMODELREQUEST']._serialized_end=206
  _globals['_GETGLOBALMODELRESPONSE']._serialized_start=208
  _globals['_GETGLOBALMODELRESPONSE']._serialized_end=323
  _globals['_SUBMITUPDATEREQUEST']._serialized_start=326
  _globals['_SUBMITUPDATEREQUEST']._serialized_end=469
  _globals['_SUBMITUPDATERESPONSE']._serialized_start=471
  _globals['_SUBMITUPDATERESPONSE']._serialized_end=594
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_start=597
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
